[colors.primary]
background = "#171C1B"
foreground = "#D4BE98"

[colors.cursor]
text = "#171C1B"
cursor = "#D4BE98"

[colors.selection]
text = "#D4BE98"
background = "#32302F"

[colors.normal]
black = "#141617"
red = "#EA6962"
green = "#A9B665"
yellow = "#D8A657"
blue = "#7DAEA3"
magenta = "#D3869B"
cyan = "#89B482"
white = "#DDC7A1"

[colors.bright]
black = "#504945"
red = "#EA6962"
green = "#A9B665"
yellow = "#D8A657"
blue = "#7DAEA3"
magenta = "#D3869B"
cyan = "#89B482"
white = "#DDC7A1"

# Extra Gruvbox Material shades (optional, can be used in Neovim/OSC sequences)
[colors.indexed]
16 = "#32302F"
17 = "#3C3836"
18 = "#442E2D"
19 = "#333E34"
20 = "#2E3B3B"
21 = "#473C29"
22 = "#3C333B"
23 = "#3C1F1E"
24 = "#32361A"
25 = "#0D3138"
26 = "#7C6F64"
27 = "#928374"
28 = "#A89984"
