# Setting a New prefix for tmux
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Split using using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %


# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind-key -n S-Left swap-window -t -1
bind-key -n S-Right swap-window -t +1
bind-key n new-window
bind-key -r C-Right next-window
bind-key -r C-Left previous-window
bind-key -r o last-window
bind -r C-h resize-pane -L 3
bind-key r command-prompt -I "#W" "rename-window '%%'"
bind -r C-j resize-pane -D 3
bind -r C-k resize-pane -U 3
bind -r C-l resize-pane -R 3

# Enable Mouse Mode
set -g mouse on

# Source File Keybind
bind R source-file ~/.tmux.conf \; display-message "Config reloaded.."

# Stop renaming of windows
set-option -g allow-rename off
set-window-option -g automatic-rename off
set -g @continuum-restore 'on'

set -g status-right ' <techtuner> '
set -g status-right-length 20





# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin "arcticicestudio/nord-tmux"

set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"


if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
