alias ls="eza --icons=always"
alias src="source ~/.zshrc"
alias gs="git status"
alias gp="git pull"
alias vim="nvim"
alias e="exit"
alias python="python3"
alias dots="cd ~/workspace/Projects/dotfiles && ls"
alias projects="cd ~/workspace/Projects/ && ls"
alias config="cd ~/.config/ && ls"
alias wall="cd ~/Pictures/wallpapers && gio open ."
alias cat="bat"
alias cd="z"