general.import = ["./themes/gruvbox-material.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.85
blur = true
dynamic_padding = true

[mouse]
hide_when_typing = true

[font]
normal.family = "SFMono Nerd Font"
size = 14

[keyboard]
bindings = [
  { key = "Left", mods = "Alt", chars = "\u001bB" },       # Skip word left
  { key = "Right", mods = "Alt", chars = "\u001bF" },      # Skip word right
  { key = "Left", mods = "Command", chars = "\u001bOH" },  # Jump line start
  { key = "Right", mods = "Command", chars = "\u001bOF" }, # Jump line end
  { key = "Back", mods = "Command", chars = "\u0015" },    # Delete line
  { key = "Back", mods = "Command", chars = "\u0017" },    # Delete word
]

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[terminal.shell]
program = "pwsh"
args = ["--nologo"]
