require('plugins')
require("options")
require("nvim-tree-config")
require("lualine-config")
require("bufferline-config")
require("autopairs-config")
require("treesitter-config")
require("keymaps")
vim.cmd([[colorscheme gruvbox]])
